#!/usr/bin/env python2
import struct
import sys
import os

def swppath(p):
  d, n = os.path.split(p)
  return os.path.abspath(os.path.join(os.getcwd(), d, '.'+n+'.swp'))

def main(lookfor):
  lookfor = swppath(lookfor)
  if not lookfor or not os.path.isfile(lookfor):
    return
  
  # vim pid is stored in bytes 24-25 of the .swp file, as a short
  with open(lookfor) as fd:
    fd.seek(24)
    pidbs = fd.read(2)
    vipid = struct.unpack("H", pidbs)[0]

  # entry 4 of the stat is the parent pid of vim
  with open('/proc/%d/stat' % vipid) as stat:
    scpid = int(stat.read().split()[3])

  # check to be sure that vim's parent process is a screen (SCREEN) session
  with open('/proc/%d/cmdline' % scpid) as cmdline:
    if 'SCREEN' not in cmdline.read():
      return

  print scpid

main(sys.argv[1])

